SET IDENTITY_INSERT PaymentTypes OFF;
SET IDENTITY_INSERT TrashTypes OFF;
SET IDENTITY_INSERT AdminRoles OFF;

SET IDENTITY_INSERT Customers OFF;
SET IDENTITY_INSERT Admins OFF;
SET IDENTITY_INSERT TrashCollectors OFF;
SET IDENTITY_INSERT Locations OFF;
SET IDENTITY_INSERT GarbageCenters OFF;

SET IDENTITY_INSERT Transactions OFF;
SET IDENTITY_INSERT TransactionItems OFF;
SET IDENTITY_INSERT Reports OFF;
SET IDENTITY_INSERT ReportItems OFF;
SET IDENTITY_INSERT TrashSales OFF;
SET IDENTITY_INSERT TrashSaleItems OFF;
SET IDENTITY_INSERT Withdrawals OFF;
