INSERT INTO GarbageCenters VALUES('Minnesota','Comcast, Ely  Hill 9273, Garland, PRT 5558');
INSERT INTO GarbageCenters VALUES('Iowa','It Smart Group, Norland  Way 4786, Paris, NPL 3786');
INSERT INTO GarbageCenters VALUES('Montana','21st Century Fox, Bagford   Vale 8633, Saint Paul, MKD 2025');
INSERT INTO GarbageCenters VALUES('Massachusetts','UPC, Cave   Avenue 9939, Otawa, GHA 2552');
INSERT INTO GarbageCenters VALUES('Illinois','Metro Cash&Carry, Dunsley  Grove 5239, Lincoln, GUM 3743');
INSERT INTO GarbageCenters VALUES('Pennsylvania','ExxonMobil, Vine  Road 7965, Indianapolis, TCD 8246');
INSERT INTO GarbageCenters VALUES('Kentucky','Vodafone, Elia   Crossroad 9685, Paris, BFA 2531');
INSERT INTO GarbageCenters VALUES('Maine','BuzzFeed, Egerton  Alley 4295, Fayetteville, GUM 5640');
INSERT INTO GarbageCenters VALUES('Idaho','Danone, Callcott   Road 9421, Honolulu, MKD 5526');
INSERT INTO GarbageCenters VALUES('South Carolina','Facebook, Edwin   Grove 6689, Toledo, SWE 5578');
INSERT INTO GarbageCenters VALUES('Kansas','UPC, Fawn Drive 6980, Quebec, CYM 2571');
INSERT INTO GarbageCenters VALUES('Tennessee','Biolife Grup, Aspen Lane 9568, Jersey City, HUN 4867');
INSERT INTO GarbageCenters VALUES('Idaho','It Smart Group, Rivervalley Tunnel 9706, Valetta, MAF 1081');
INSERT INTO GarbageCenters VALUES('Montana','Areon Impex, Norland  Route 9896, Kansas City, TCD 0358');
INSERT INTO GarbageCenters VALUES('Georgia','Comodo, Camberwell  Way 7648, Henderson, SSD 7082');
INSERT INTO GarbageCenters VALUES('Maine','Amazon.com, Thurloe   Hill 4306, Milwaukee, MSR 6372');
INSERT INTO GarbageCenters VALUES('Vermont','Comodo, Fairholt   Grove 5692, Memphis, LUX 7831');
INSERT INTO GarbageCenters VALUES('Colorado','Biolife Grup, Gate   Alley 3593, Dallas, ESH 0182');
INSERT INTO GarbageCenters VALUES('Pennsylvania','Telekom, Fair Lane 4464, Jacksonville, AND 7620');
INSERT INTO GarbageCenters VALUES('Maine','Telekom, Yorkshire  Pass 3245, San Diego, TLS 2188');
INSERT INTO GarbageCenters VALUES('Arkansas','21st Century Fox, Howard Street 3637, Phoenix, SPM 2352');
INSERT INTO GarbageCenters VALUES('Missouri','Facebook, King William  Lane 6426, San Antonio, IDN 1158');
INSERT INTO GarbageCenters VALUES('Idaho','Erickson, Paris   Lane 6512, Nashville, IOT 0863');
INSERT INTO GarbageCenters VALUES('New Mexico','Leadertech Consulting, Badric  Alley 2524, Valetta, CRI 2374');
INSERT INTO GarbageCenters VALUES('North Carolina','Leadertech Consulting, Lake Grove 4236, Berlin, NIC 3872');
INSERT INTO GarbageCenters VALUES('Arkansas','Zepter, Lexington Avenue 4603, Lisbon, ATG 3364');
INSERT INTO GarbageCenters VALUES('Texas','21st Century Fox, Cliffords  Way 5537, San Diego, CPV 2821');
INSERT INTO GarbageCenters VALUES('Missouri','Erickson, Camley   Grove 2092, Honolulu, WLF 8474');
INSERT INTO GarbageCenters VALUES('Kansas','ENEL, Walnut Hill 7573, Amarillo, TLS 8836');
INSERT INTO GarbageCenters VALUES('New Mexico','ExxonMobil, Baylis  Pass 7961, San Francisco, MLT 0688');
INSERT INTO GarbageCenters VALUES('Nevada','Demaco, Westbourne Boulevard 330, Hayward, NIU 4426');
INSERT INTO GarbageCenters VALUES('Utah','Comodo, Belmore  Road 9827, Baltimore, GUY 2826');
INSERT INTO GarbageCenters VALUES('Indiana','BuzzFeed, Bel   Street 4825, Bakersfield, MLT 3415');
INSERT INTO GarbageCenters VALUES('Washington','Leadertech Consulting, Wake  Route 4122, Berlin, UGA 5483');
INSERT INTO GarbageCenters VALUES('Texas','Demaco, Biggerstaff   Grove 7385, London, ZWE 4385');
INSERT INTO GarbageCenters VALUES('Wyoming','It Smart Group, Linden Drive 8383, Long Beach, DNK 8174');
INSERT INTO GarbageCenters VALUES('Idaho','DynCorp, Champion  Alley 5983, Madrid, JPN 1276');
INSERT INTO GarbageCenters VALUES('Connecticut','It Smart Group, Balfour    Road 195, San Francisco, MSR 4866');
INSERT INTO GarbageCenters VALUES('Montana','Comcast, Bacton   Alley 4174, Fayetteville, HUN 3574');
INSERT INTO GarbageCenters VALUES('Kansas','Coca-Cola Company, Durnford  Pass 6638, Colorado Springs, PAK 8156');
INSERT INTO GarbageCenters VALUES('Vermont','Danone, Camley   Tunnel 8331, Nashville, MDV 6586');
INSERT INTO GarbageCenters VALUES('Alabama','Vodafone, Glenwood Tunnel 5116, Las Vegas, ESP 3827');
INSERT INTO GarbageCenters VALUES('New York','Areon Impex, Longleigh   Way 2810, Otawa, ESH 1850');
INSERT INTO GarbageCenters VALUES('Nebraska','Areon Impex, Paris   Lane 1816, Innsbruck, TUR 3725');
INSERT INTO GarbageCenters VALUES('Indiana','It Smart Group, Garfield Route 4122, Arlington, LAO 4764');
INSERT INTO GarbageCenters VALUES('Georgia','Biolife Grup, Clarks  Avenue 2075, Milwaukee, BEN 2381');
INSERT INTO GarbageCenters VALUES('Alaska','Comcast, Walnut Hill 5739, Santa Ana, PCN 7445');
INSERT INTO GarbageCenters VALUES('Oklahoma','AECOM, Castle Grove 8956, Tallahassee, ERI 6462');
INSERT INTO GarbageCenters VALUES('Illinois','Metro Cash&Carry, Pine Pass 6728, Milwaukee, ABW 1585');
INSERT INTO GarbageCenters VALUES('Washington','Erickson, Black Swan  Drive 8603, Otawa, AND 1818');
