INSERT INTO Locations VALUES ('Villa Serrano', '75 Schurz Parkway');
INSERT INTO Locations VALUES ('Zandak', '515 Hoffman Circle');
INSERT INTO Locations VALUES ('Villarrica', '4 Reinke Junction');
INSERT INTO Locations VALUES ('Grubišno Polje', '2 Summer Ridge Drive');
INSERT INTO Locations VALUES ('Beloeil', '21 Sunfield Point');
INSERT INTO Locations VALUES ('Itatiba', '1 Brown Crossing');
INSERT INTO Locations VALUES ('Dake', '871 Golf Course Terrace');
INSERT INTO Locations VALUES ('Tangyin', '6835 Duke Place');
INSERT INTO Locations VALUES ('Silvares', '5347 Scott Hill');
INSERT INTO Locations VALUES ('Zheleznogorsk', '398 Nancy Trail');
INSERT INTO Locations VALUES ('Lipnik', '8 Paget Crossing');
INSERT INTO Locations VALUES ('Kihniö', '9 Glacier Hill Court');
INSERT INTO Locations VALUES ('San José Poaquil', '578 Mcbride Drive');
INSERT INTO Locations VALUES ('Shuishiying', '2 Meadow Ridge Avenue');
INSERT INTO Locations VALUES ('Nakhodka', '469 Almo Avenue');
INSERT INTO Locations VALUES ('Donnycarney', '15321 Crest Line Terrace');
INSERT INTO Locations VALUES ('Lingcheng', '6 Nancy Plaza');
INSERT INTO Locations VALUES ('Oekero', '6 Marquette Circle');
INSERT INTO Locations VALUES ('Combapata', '92947 Victoria Alley');
INSERT INTO Locations VALUES ('Kamieniec', '63 Kedzie Trail');
INSERT INTO Locations VALUES ('Pretana', '9917 Mitchell Way');
INSERT INTO Locations VALUES ('Apače', '4 Almo Trail');
INSERT INTO Locations VALUES ('Larache', '880 Pearson Hill');
INSERT INTO Locations VALUES ('Cambebba', '5 Bartelt Trail');
INSERT INTO Locations VALUES ('Nakhon Nayok', '13 Harbort Point');
INSERT INTO Locations VALUES ('Zwolle', '36 Nobel Street');
INSERT INTO Locations VALUES ('Boyle', '51520 Loeprich Crossing');
INSERT INTO Locations VALUES ('Elverum', '73932 Havey Hill');
INSERT INTO Locations VALUES ('Vitanje', '8 Hayes Lane');
INSERT INTO Locations VALUES ('Jindayris', '93015 5th Parkway');
INSERT INTO Locations VALUES ('Menggusi', '14 Graedel Park');
INSERT INTO Locations VALUES ('Palilula', '249 Lakewood Circle');
INSERT INTO Locations VALUES ('Tunggaoen Timur', '02699 Vernon Terrace');
INSERT INTO Locations VALUES ('Västra Frölunda', '366 Spohn Circle');
INSERT INTO Locations VALUES ('Baihe', '015 Lyons Court');
INSERT INTO Locations VALUES ('Morelos', '81 Myrtle Parkway');
INSERT INTO Locations VALUES ('Kasembon', '311 Transport Point');
INSERT INTO Locations VALUES ('Cuijiaqiao', '8 Maryland Place');
INSERT INTO Locations VALUES ('Edineţ', '4 Straubel Avenue');
INSERT INTO Locations VALUES ('Villa Florida', '593 Barnett Junction');
INSERT INTO Locations VALUES ('Cayambe', '7 Macpherson Point');
INSERT INTO Locations VALUES ('Kohtla-Järve', '7 Pearson Trail');
INSERT INTO Locations VALUES ('Huangtu', '96 Pennsylvania Crossing');
INSERT INTO Locations VALUES ('Charras', '32341 Hoffman Court');
INSERT INTO Locations VALUES ('Cheongpyeong', '5 Lyons Alley');
INSERT INTO Locations VALUES ('Sanjiang', '710 Monica Pass');
INSERT INTO Locations VALUES ('Genova', '1 Swallow Hill');
INSERT INTO Locations VALUES ('Vári', '40046 Troy Drive');
INSERT INTO Locations VALUES ('Dongtang', '4 Eastwood Street');
INSERT INTO Locations VALUES ('Zlatoust', '96364 Superior Lane');
INSERT INTO Locations VALUES ('Borås', '0610 Dawn Parkway');
INSERT INTO Locations VALUES ('Grojec', '5 Scott Drive');
INSERT INTO Locations VALUES ('Nankun', '823 Carberry Hill');
INSERT INTO Locations VALUES ('Yaguachi Nuevo', '9 Bunker Hill Court');
INSERT INTO Locations VALUES ('Krajan Pangkah Kulon', '43414 Northview Plaza');
INSERT INTO Locations VALUES ('Lamduan', '3187 Coleman Trail');
INSERT INTO Locations VALUES ('Amphawa', '90015 Barnett Crossing');
INSERT INTO Locations VALUES ('Pacaraos', '33768 Stuart Way');
INSERT INTO Locations VALUES ('Gaio', '58871 Mallory Lane');
INSERT INTO Locations VALUES ('Moss', '1800 Spenser Road');
INSERT INTO Locations VALUES ('New York City', '59 International Hill');
INSERT INTO Locations VALUES ('Zaragoza', '36 Becker Crossing');
INSERT INTO Locations VALUES ('Binitayan', '43 Warner Way');
INSERT INTO Locations VALUES ('El Peñol', '77764 Anzinger Pass');
INSERT INTO Locations VALUES ('Krajanbonjor', '06728 Northport Pass');
INSERT INTO Locations VALUES ('Pasto', '02334 Drewry Park');
INSERT INTO Locations VALUES ('Erdu', '42407 John Wall Hill');
INSERT INTO Locations VALUES ('Cosmópolis', '40 Golf Course Circle');
INSERT INTO Locations VALUES ('Dmytrivka', '430 Ilene Hill');
INSERT INTO Locations VALUES ('Cibolek Kidul', '489 Bunker Hill Hill');
INSERT INTO Locations VALUES ('Mūdīyah', '293 Farragut Street');
INSERT INTO Locations VALUES ('Dřevohostice', '14 Dayton Alley');
INSERT INTO Locations VALUES ('Al Manşūrah', '22299 Twin Pines Park');
INSERT INTO Locations VALUES ('Dār Kulayb', '9439 Lakewood Terrace');
INSERT INTO Locations VALUES ('Cikawung', '4 Lotheville Street');
INSERT INTO Locations VALUES ('Atamanovka', '03784 Prairie Rose Place');
INSERT INTO Locations VALUES ('Ajman', '8078 Fisk Point');
INSERT INTO Locations VALUES ('Kloangpopot', '575 Larry Court');
INSERT INTO Locations VALUES ('Goubétto', '89 Melrose Junction');
INSERT INTO Locations VALUES ('Astanajapura', '42302 Delladonna Terrace');
INSERT INTO Locations VALUES ('Zaqatala', '72 Kingsford Alley');
INSERT INTO Locations VALUES ('Dublje', '74201 Luster Park');
INSERT INTO Locations VALUES ('Liaodian', '1516 Vahlen Point');
INSERT INTO Locations VALUES ('Lubukgadang', '456 Oneill Road');
INSERT INTO Locations VALUES ('Zielona Góra', '5 Claremont Alley');
INSERT INTO Locations VALUES ('Suka Makmue', '77 Stoughton Way');
INSERT INTO Locations VALUES ('Shuanggang', '5 Ilene Court');
INSERT INTO Locations VALUES ('Ruokolahti', '52 Dorton Court');
INSERT INTO Locations VALUES ('Węgrzce Wielkie', '88 Ronald Regan Park');
INSERT INTO Locations VALUES ('Danchang', '815 Sullivan Drive');
INSERT INTO Locations VALUES ('Guéret', '735 Eagan Place');
INSERT INTO Locations VALUES ('San Jose', '4825 Montana Parkway');
INSERT INTO Locations VALUES ('Falun', '90 Transport Road');
INSERT INTO Locations VALUES ('Ujmisht', '8 Lerdahl Place');
INSERT INTO Locations VALUES ('Taklale', '1 Buhler Center');
INSERT INTO Locations VALUES ('Campos do Jordão', '5772 Melody Terrace');
INSERT INTO Locations VALUES ('Albany', '4735 Warner Road');
INSERT INTO Locations VALUES ('Chajarí', '499 Quincy Terrace');
INSERT INTO Locations VALUES ('Jiangkou', '8757 Comanche Circle');
INSERT INTO Locations VALUES ('Tumpang', '5276 Service Park');
INSERT INTO Locations VALUES ('Lopandino', '0628 Leroy Crossing');
INSERT INTO Locations VALUES ('Marinha', '1 Warrior Trail');
INSERT INTO Locations VALUES ('Ituiutaba', '7 Blackbird Way');
INSERT INTO Locations VALUES ('Česká Skalice', '3809 Hallows Circle');
INSERT INTO Locations VALUES ('Xiasha', '57 Charing Cross Circle');
INSERT INTO Locations VALUES ('Haradzyeya', '8754 Hagan Street');
INSERT INTO Locations VALUES ('Ellös', '201 Bartelt Court');
INSERT INTO Locations VALUES ('Jialai', '87731 Havey Street');
INSERT INTO Locations VALUES ('Ḩalāwah', '017 Golden Leaf Crossing');
INSERT INTO Locations VALUES ('Pueblo Nuevo Viñas', '6 Village Green Point');
INSERT INTO Locations VALUES ('Daloa', '29386 Sycamore Crossing');
INSERT INTO Locations VALUES ('Lipovci', '57647 Daystar Hill');
INSERT INTO Locations VALUES ('Tam Kỳ', '4 Sutherland Place');
INSERT INTO Locations VALUES ('Omaha', '1232 Everett Trail');
INSERT INTO Locations VALUES ('San Miguel de Tucumán', '281 Anthes Hill');
INSERT INTO Locations VALUES ('San Vicente', '4 Sachtjen Place');
INSERT INTO Locations VALUES ('Novozybkov', '80 Westport Center');
INSERT INTO Locations VALUES ('Ploemeur', '2102 Katie Lane');
INSERT INTO Locations VALUES ('Ipoti', '352 Harbort Hill');
INSERT INTO Locations VALUES ('Okhtyrka', '6048 Logan Park');
INSERT INTO Locations VALUES ('Puan', '6 Bartillon Road');
INSERT INTO Locations VALUES ('Sandaohezi', '861 Talmadge Crossing');
INSERT INTO Locations VALUES ('Kyrenia', '76609 Onsgard Crossing');
INSERT INTO Locations VALUES ('Venlo', '1 Bartelt Road');
INSERT INTO Locations VALUES ('Larvik', '0766 Manley Drive');
INSERT INTO Locations VALUES ('Nor Gyugh', '9 Schurz Way');
INSERT INTO Locations VALUES ('Yanfolila', '42101 Anniversary Way');
INSERT INTO Locations VALUES ('Rawaglagah', '60622 Holy Cross Parkway');
INSERT INTO Locations VALUES ('Danan', '187 School Crossing');
INSERT INTO Locations VALUES ('Debre Zeyit', '9363 Lawn Circle');
INSERT INTO Locations VALUES ('Tanbu', '361 Arapahoe Lane');
INSERT INTO Locations VALUES ('Pescadería', '5 Elka Parkway');
INSERT INTO Locations VALUES ('Growong Lor', '91 Jenna Lane');
INSERT INTO Locations VALUES ('Roanoke', '343 Pepper Wood Terrace');
INSERT INTO Locations VALUES ('Al Ma‘allā’', '48 Fair Oaks Lane');
INSERT INTO Locations VALUES ('Pledo', '15 Moose Plaza');
INSERT INTO Locations VALUES ('Bunia', '3 Bay Parkway');
INSERT INTO Locations VALUES ('Lagos', '37 Dottie Way');
INSERT INTO Locations VALUES ('Kuantan', '69160 Pearson Place');
INSERT INTO Locations VALUES ('Novosin’kovo', '3732 Manufacturers Circle');
INSERT INTO Locations VALUES ('Nanping', '0 Lotheville Lane');
INSERT INTO Locations VALUES ('Ratchaburi', '9 Weeping Birch Parkway');
INSERT INTO Locations VALUES ('Khān Neshīn', '17104 Tennyson Junction');
INSERT INTO Locations VALUES ('Huangzhan', '1 Sachtjen Hill');
INSERT INTO Locations VALUES ('Haliut', '817 Hagan Lane');
INSERT INTO Locations VALUES ('Cadiz', '66 Judy Drive');
INSERT INTO Locations VALUES ('Dalun', '792 Raven Point');
INSERT INTO Locations VALUES ('Baiyang', '887 Fremont Park');
INSERT INTO Locations VALUES ('Ferrol', '5629 Talmadge Hill');
INSERT INTO Locations VALUES ('Tanjungagung', '3 Randy Park');
INSERT INTO Locations VALUES ('Norfolk', '2 Northland Point');
INSERT INTO Locations VALUES ('Nantes', '4 Washington Street');
INSERT INTO Locations VALUES ('Jankowice', '81055 Memorial Crossing');
INSERT INTO Locations VALUES ('Cahul', '3 Montana Place');
INSERT INTO Locations VALUES ('General Vedia', '79 John Wall Hill');
INSERT INTO Locations VALUES ('Cihua', '3842 Spenser Trail');
INSERT INTO Locations VALUES ('Banjar Pekandelan', '783 Garrison Place');
INSERT INTO Locations VALUES ('Krasnoarmiys’k', '873 Talmadge Point');
INSERT INTO Locations VALUES ('Colquemarca', '4377 Forest Run Point');
INSERT INTO Locations VALUES ('Junbu', '3358 Weeping Birch Place');
INSERT INTO Locations VALUES ('Guadalupe', '0 Commercial Alley');
INSERT INTO Locations VALUES ('Aksu', '73758 Steensland Trail');
INSERT INTO Locations VALUES ('Nazaré da Mata', '5080 Buena Vista Point');
INSERT INTO Locations VALUES ('Abreus', '9 Larry Hill');
INSERT INTO Locations VALUES ('Jiangbei', '2 Almo Crossing');
INSERT INTO Locations VALUES ('Diamantina', '835 Declaration Trail');
INSERT INTO Locations VALUES ('Javalera', '66818 Corry Avenue');
INSERT INTO Locations VALUES ('Ust’-Ilimsk', '6362 Namekagon Parkway');
INSERT INTO Locations VALUES ('Jianfeng', '20 Bowman Lane');
INSERT INTO Locations VALUES ('Buluh Kasap', '7 Burning Wood Lane');
INSERT INTO Locations VALUES ('Siyabuswa', '1 Truax Plaza');
INSERT INTO Locations VALUES ('Crépy-en-Valois', '14700 Spohn Street');
INSERT INTO Locations VALUES ('Rogongon', '91 Sauthoff Trail');
INSERT INTO Locations VALUES ('Vĩnh Thuận', '9096 Longview Crossing');
INSERT INTO Locations VALUES ('San Lorenzo', '87942 Larry Court');
INSERT INTO Locations VALUES ('Matou', '4952 Talmadge Trail');
INSERT INTO Locations VALUES ('Magang', '976 Continental Pass');
INSERT INTO Locations VALUES ('Rejoyoso', '8164 Randy Court');
INSERT INTO Locations VALUES ('Działdowo', '717 Moland Park');
INSERT INTO Locations VALUES ('Numan', '70314 Eastwood Avenue');
INSERT INTO Locations VALUES ('Makoko', '86 Kedzie Hill');
INSERT INTO Locations VALUES ('Fenoarivo Atsinanana', '278 Macpherson Junction');
INSERT INTO Locations VALUES ('Qingshui', '4894 Maywood Parkway');
INSERT INTO Locations VALUES ('Wengtian', '0771 Kings Plaza');
INSERT INTO Locations VALUES ('Tāybād', '71647 Bunker Hill Lane');
INSERT INTO Locations VALUES ('Santa Rita', '06 Barnett Junction');
INSERT INTO Locations VALUES ('Lindavista', '52 Fallview Avenue');
INSERT INTO Locations VALUES ('Hoopstad', '31383 Carpenter Hill');
INSERT INTO Locations VALUES ('Bangrat', '9 Debs Drive');
INSERT INTO Locations VALUES ('Abades', '8070 Duke Pass');
INSERT INTO Locations VALUES ('Shuitianhe', '57 Melvin Crossing');
INSERT INTO Locations VALUES ('Salisbury', '30020 Meadow Vale Drive');
INSERT INTO Locations VALUES ('Libiąż', '91814 Oakridge Place');
INSERT INTO Locations VALUES ('Correia Pinto', '8226 Gateway Alley');
INSERT INTO Locations VALUES ('Zhangjiawo', '64 Lotheville Terrace');
INSERT INTO Locations VALUES ('Landskrona', '298 Pennsylvania Avenue');
INSERT INTO Locations VALUES ('Kisai', '04 Pennsylvania Junction');
INSERT INTO Locations VALUES ('Pastores', '9 Fuller Center');
INSERT INTO Locations VALUES ('Las Piñas', '2946 Logan Drive');
INSERT INTO Locations VALUES ('Adstock', '6421 Petterle Hill');
INSERT INTO Locations VALUES ('Pāvilosta', '5555 Vidon Road');
INSERT INTO Locations VALUES ('Kantemirovka', '613 Green Junction');
INSERT INTO Locations VALUES ('Sanlicheng', '6 Annamark Hill');
INSERT INTO Locations VALUES ('Tayasan', '353 Rowland Way');
INSERT INTO Locations VALUES ('Nowy Staw', '2588 Clemons Crossing');
INSERT INTO Locations VALUES ('Merke', '182 Rieder Drive');
INSERT INTO Locations VALUES ('Lantian', '28 Comanche Alley');
INSERT INTO Locations VALUES ('Ijuí', '1189 Dryden Way');
INSERT INTO Locations VALUES ('Yangqiaodian', '182 Mesta Drive');
INSERT INTO Locations VALUES ('Depok', '809 Macpherson Lane');
INSERT INTO Locations VALUES ('Montes Claros', '2 Scott Plaza');
INSERT INTO Locations VALUES ('Pangu', '86 Corry Park');
INSERT INTO Locations VALUES ('Novocheboksarsk', '5764 Village Green Road');
INSERT INTO Locations VALUES ('Goyang-si', '21931 Eastwood Trail');
INSERT INTO Locations VALUES ('Krajan Gebangan', '34179 Tennyson Way');
INSERT INTO Locations VALUES ('El Real', '032 Trailsway Terrace');
INSERT INTO Locations VALUES ('Ngreco', '1 Starling Street');
INSERT INTO Locations VALUES ('Zhapu', '68379 Shelley Plaza');
INSERT INTO Locations VALUES ('Batur Kidul', '98772 Namekagon Hill');
INSERT INTO Locations VALUES ('Shencun', '0 Bunker Hill Point');
INSERT INTO Locations VALUES ('Křižanov', '082 Upham Junction');
INSERT INTO Locations VALUES ('Vila do Maio', '315 Sunnyside Plaza');
INSERT INTO Locations VALUES ('Gentilly', '043 Village Green Pass');
INSERT INTO Locations VALUES ('Cileunyi', '69180 Independence Park');
INSERT INTO Locations VALUES ('Pionerskiy', '17098 Helena Terrace');
INSERT INTO Locations VALUES ('Wang Sombun', '90 Ronald Regan Court');
INSERT INTO Locations VALUES ('Voiron', '8 Emmet Road');
INSERT INTO Locations VALUES ('Bắc Kạn', '566 Maple Street');
INSERT INTO Locations VALUES ('Laḩij', '417 Mariners Cove Plaza');
INSERT INTO Locations VALUES ('Porto Calvo', '65657 Thierer Junction');
INSERT INTO Locations VALUES ('Hwaseong-si', '5020 Hooker Center');
INSERT INTO Locations VALUES ('Södertälje', '6423 Waxwing Trail');
INSERT INTO Locations VALUES ('Lapachito', '30 Tomscot Pass');
INSERT INTO Locations VALUES ('Xiejiatan', '445 Florence Avenue');
INSERT INTO Locations VALUES ('Baturaja', '370 Bartelt Terrace');
INSERT INTO Locations VALUES ('Verkhnyaya Toyma', '54966 Glendale Plaza');
INSERT INTO Locations VALUES ('Río Tercero', '12 Corscot Point');
INSERT INTO Locations VALUES ('Carhuac', '8 Lillian Way');
INSERT INTO Locations VALUES ('Torbeyevo', '6 Di Loreto Parkway');
INSERT INTO Locations VALUES ('‘Ubāl', '4841 Cody Crossing');
INSERT INTO Locations VALUES ('Guansheng', '251 Oneill Drive');
INSERT INTO Locations VALUES ('Forécariah', '8 Cottonwood Hill');
INSERT INTO Locations VALUES ('Mölnlycke', '5 Nova Court');
INSERT INTO Locations VALUES ('Little Baguio', '07 Emmet Pass');
INSERT INTO Locations VALUES ('Znamenskoye', '7562 Oneill Street');
INSERT INTO Locations VALUES ('Ust’-Dzheguta', '93 Fremont Court');
INSERT INTO Locations VALUES ('Krasnoyarka', '07174 Sage Trail');
INSERT INTO Locations VALUES ('Zhangatas', '8574 Harper Trail');
INSERT INTO Locations VALUES ('Biltine', '7 7th Trail');
INSERT INTO Locations VALUES ('Loo', '8040 Fisk Circle');
INSERT INTO Locations VALUES ('Shapaja', '0 Florence Center');
INSERT INTO Locations VALUES ('Kanash', '17 Dixon Plaza');
INSERT INTO Locations VALUES ('Sukorejo', '85 Jay Center');
INSERT INTO Locations VALUES ('Xuyong', '531 Brentwood Court');
INSERT INTO Locations VALUES ('Dadap', '640 Stone Corner Place');
INSERT INTO Locations VALUES ('Alegria', '0 Hoepker Trail');
INSERT INTO Locations VALUES ('Mujães', '2 Michigan Trail');
INSERT INTO Locations VALUES ('Yangdang', '4 Dahle Pass');
INSERT INTO Locations VALUES ('Queluz', '6744 Muir Crossing');
INSERT INTO Locations VALUES ('Nanhuang', '9798 Macpherson Park');
INSERT INTO Locations VALUES ('Xinshi', '45 Mccormick Road');
INSERT INTO Locations VALUES ('Lingdi', '2 Mifflin Way');
INSERT INTO Locations VALUES ('Intibucá', '7 Columbus Terrace');
INSERT INTO Locations VALUES ('Néos Skopós', '9 Melvin Trail');
INSERT INTO Locations VALUES ('Zhlobin', '876 School Terrace');
INSERT INTO Locations VALUES ('Nangerang', '747 8th Center');
INSERT INTO Locations VALUES ('Jiaokou', '0681 Johnson Parkway');
INSERT INTO Locations VALUES ('Fonte Boa', '5677 Independence Crossing');
INSERT INTO Locations VALUES ('Maracanaú', '943 Onsgard Street');
INSERT INTO Locations VALUES ('Muḩambal', '66056 Forster Pass');
INSERT INTO Locations VALUES ('Emalgolin Mongolzuxiang', '38381 Swallow Junction');
INSERT INTO Locations VALUES ('Asopós', '2920 Pierstorff Trail');
INSERT INTO Locations VALUES ('Loma Bonita', '89 Miller Parkway');
INSERT INTO Locations VALUES ('Qiaotou', '58 Northland Plaza');
INSERT INTO Locations VALUES ('Huangze', '75730 Southridge Road');
INSERT INTO Locations VALUES ('San Isidro', '50 Ruskin Trail');
INSERT INTO Locations VALUES ('Budaka', '70721 Amoth Court');
INSERT INTO Locations VALUES ('Shiqiao', '8552 Graedel Center');
INSERT INTO Locations VALUES ('Yushu', '21002 Golf Course Drive');
INSERT INTO Locations VALUES ('Hongqi', '1 David Park');
INSERT INTO Locations VALUES ('Komes', '92 Sachtjen Hill');
INSERT INTO Locations VALUES ('Ngilengan', '11788 Spenser Place');
INSERT INTO Locations VALUES ('Junyang', '83521 Ohio Road');
INSERT INTO Locations VALUES ('El Corozo', '0760 Atwood Avenue');
INSERT INTO Locations VALUES ('Saint-Denis', '80 Anhalt Street');
INSERT INTO Locations VALUES ('Yangdi', '98 Jenna Court');
INSERT INTO Locations VALUES ('Älvsjö', '287 Kinsman Place');
INSERT INTO Locations VALUES ('Tunguang', '86 Melvin Crossing');
INSERT INTO Locations VALUES ('Gaotuan', '785 Stone Corner Circle');
INSERT INTO Locations VALUES ('Luwan', '93250 Starling Junction');
INSERT INTO Locations VALUES ('Sundsvall', '255 Pennsylvania Park');
INSERT INTO Locations VALUES ('Bystřice nad Pernštejnem', '4149 Beilfuss Circle');
INSERT INTO Locations VALUES ('Liucheng', '8 Waywood Trail');
INSERT INTO Locations VALUES ('Louriceira', '347 Vera Crossing');
INSERT INTO Locations VALUES ('Zborovice', '8742 Anthes Drive');
INSERT INTO Locations VALUES ('Dhī Nā‘im', '9979 Talisman Pass');
INSERT INTO Locations VALUES ('Longsheng', '24 La Follette Junction');
INSERT INTO Locations VALUES ('Zelenchukskaya', '66750 Wayridge Center');
INSERT INTO Locations VALUES ('Shengshan', '79720 Hoepker Plaza');
INSERT INTO Locations VALUES ('Vlachovice', '73 Bayside Junction');
INSERT INTO Locations VALUES ('Mandalt', '8 Lakewood Gardens Road');
INSERT INTO Locations VALUES ('Abangay', '71589 Monument Lane');
INSERT INTO Locations VALUES ('Shima', '7 Morning Parkway');
INSERT INTO Locations VALUES ('H̱olon', '1 Knutson Circle');
INSERT INTO Locations VALUES ('Fovissste', '8882 Moose Center');
INSERT INTO Locations VALUES ('Daoxian', '7 Loftsgordon Avenue');
INSERT INTO Locations VALUES ('Miratejo', '64 Autumn Leaf Court');
INSERT INTO Locations VALUES ('Podgórzyn', '487 Arkansas Road');
INSERT INTO Locations VALUES ('Daijiaba', '71 New Castle Street');
INSERT INTO Locations VALUES ('Masantol', '80 Leroy Avenue');
INSERT INTO Locations VALUES ('Horten', '7 Brickson Park Pass');
INSERT INTO Locations VALUES ('Zhob', '5 Packers Drive');
INSERT INTO Locations VALUES ('Nabīnagar', '01 Forest Run Park');
INSERT INTO Locations VALUES ('Gbarnga', '26455 Fieldstone Lane');
INSERT INTO Locations VALUES ('Jiudu', '49 Hintze Junction');
INSERT INTO Locations VALUES ('Obikiik', '0134 Northridge Place');
INSERT INTO Locations VALUES ('Hiratachō', '42 Cody Lane');
INSERT INTO Locations VALUES ('Khilok', '4640 Bonner Point');
INSERT INTO Locations VALUES ('Kimanuit', '17950 Stuart Crossing');
INSERT INTO Locations VALUES ('Al ‘Azīzīyah', '190 Erie Center');
INSERT INTO Locations VALUES ('Pakapasan Girang', '65129 Ludington Terrace');
INSERT INTO Locations VALUES ('Bāmyān', '4 Sherman Hill');
INSERT INTO Locations VALUES ('Machala', '67 Stoughton Court');
INSERT INTO Locations VALUES ('Boromlya', '22099 Fairfield Lane');
INSERT INTO Locations VALUES ('Nymburk', '0811 Summer Ridge Point');
INSERT INTO Locations VALUES ('Qorovulbozor Shahri', '15884 Parkside Trail');
INSERT INTO Locations VALUES ('Tigpalay', '500 Hudson Parkway');
INSERT INTO Locations VALUES ('Losino-Petrovskiy', '08000 Waxwing Hill');
INSERT INTO Locations VALUES ('Perez', '0 Magdeline Center');
INSERT INTO Locations VALUES ('Uppsala', '42416 Forest Circle');
INSERT INTO Locations VALUES ('Tuwiri Wetan', '0112 Hoard Plaza');
INSERT INTO Locations VALUES ('Ostružnica', '882 3rd Crossing');
INSERT INTO Locations VALUES ('Nioki', '7 Welch Center');
INSERT INTO Locations VALUES ('Chengxi', '80450 Weeping Birch Avenue');
INSERT INTO Locations VALUES ('Pakkat', '5975 Hallows Pass');
INSERT INTO Locations VALUES ('Povenets', '4391 Dwight Trail');
INSERT INTO Locations VALUES ('Barbacena', '15684 Michigan Center');
INSERT INTO Locations VALUES ('Chengdong', '55 Derek Alley');
INSERT INTO Locations VALUES ('Pueblo Nuevo', '36670 Barnett Road');
INSERT INTO Locations VALUES ('Nsukka', '3676 Transport Place');
INSERT INTO Locations VALUES ('Qincheng', '2294 Doe Crossing Junction');
INSERT INTO Locations VALUES ('Newton', '3948 Warrior Way');
INSERT INTO Locations VALUES ('Uppsala', '0603 Mcguire Alley');
INSERT INTO Locations VALUES ('Almendra', '74760 Manitowish Street');
INSERT INTO Locations VALUES ('Gunan', '75 Aberg Street');
INSERT INTO Locations VALUES ('Kandangan', '784 Daystar Avenue');
INSERT INTO Locations VALUES ('Pasadena', '27286 Oak Lane');
INSERT INTO Locations VALUES ('Rozivka', '076 Green Ridge Road');
INSERT INTO Locations VALUES ('Asen', '16 Mayer Hill');
INSERT INTO Locations VALUES ('Vladimir', '7 Ronald Regan Center');
INSERT INTO Locations VALUES ('Kungsör', '32 Moulton Center');
INSERT INTO Locations VALUES ('Luziânia', '7 Riverside Park');
INSERT INTO Locations VALUES ('Jaguaribe', '0635 Spenser Junction');
INSERT INTO Locations VALUES ('Yudai', '54 Talmadge Way');
INSERT INTO Locations VALUES ('Cô Tô', '92 Kensington Street');
INSERT INTO Locations VALUES ('Bahe', '9 Anzinger Lane');
INSERT INTO Locations VALUES ('Sukowono', '32657 Annamark Lane');
INSERT INTO Locations VALUES ('Budapest', '8 Hermina Drive');
INSERT INTO Locations VALUES ('Dalarik', '80 Elgar Road');
INSERT INTO Locations VALUES ('Pando', '682 Reindahl Center');
INSERT INTO Locations VALUES ('Sampaio', '43955 Buena Vista Alley');
INSERT INTO Locations VALUES ('Corrego Grande', '27881 Drewry Avenue');
INSERT INTO Locations VALUES ('Łysomice', '12 Sunfield Plaza');
INSERT INTO Locations VALUES ('Strawberry Hills', '158 Moulton Way');
INSERT INTO Locations VALUES ('Sungai Iyu', '69803 Kings Street');
INSERT INTO Locations VALUES ('Ajax', '981 Becker Junction');
INSERT INTO Locations VALUES ('Wujiayao', '6139 Surrey Alley');
INSERT INTO Locations VALUES ('Strawberry Hills', '9 Claremont Point');
INSERT INTO Locations VALUES ('Huaidian', '6881 Russell Way');
INSERT INTO Locations VALUES ('Alue Glumpang', '7 Morrow Pass');
INSERT INTO Locations VALUES ('Samokov', '8 1st Lane');
INSERT INTO Locations VALUES ('Baiima', '4 Jay Lane');
INSERT INTO Locations VALUES ('Maloyaroslavets', '99405 Farragut Park');
INSERT INTO Locations VALUES ('Timashëvsk', '0243 Shopko Junction');
INSERT INTO Locations VALUES ('Montauban', '01209 Mccormick Way');
INSERT INTO Locations VALUES ('Baiquan', '35236 Rusk Drive');
INSERT INTO Locations VALUES ('Majengo', '7621 Dayton Alley');
INSERT INTO Locations VALUES ('Muli', '8240 Northland Center');
INSERT INTO Locations VALUES ('Malvinas Argentinas', '9883 Kipling Lane');
INSERT INTO Locations VALUES ('Yingpu', '63 Schlimgen Trail');
INSERT INTO Locations VALUES ('Dalar', '2 Lakewood Crossing');
INSERT INTO Locations VALUES ('Warungawi', '89743 Pierstorff Avenue');
INSERT INTO Locations VALUES ('Canguaretama', '6202 Crownhardt Way');
INSERT INTO Locations VALUES ('Tanjungbalai', '6 Springview Plaza');
INSERT INTO Locations VALUES ('Baoluan', '23 Rigney Alley');
INSERT INTO Locations VALUES ('Chwaszczyno', '9055 Saint Paul Pass');
INSERT INTO Locations VALUES ('Astara', '865 Everett Circle');
INSERT INTO Locations VALUES ('Almargem do Bispo', '9 Sullivan Terrace');
INSERT INTO Locations VALUES ('Krajan Suko Kidul', '3986 Crownhardt Parkway');
INSERT INTO Locations VALUES ('Orly', '268 David Hill');
INSERT INTO Locations VALUES ('Muang Phôn-Hông', '33 Memorial Plaza');
INSERT INTO Locations VALUES ('Borek', '9 Muir Crossing');
INSERT INTO Locations VALUES ('Rancho Viejo', '62 Colorado Place');
INSERT INTO Locations VALUES ('Cigaluh', '3 Village Green Drive');
INSERT INTO Locations VALUES ('Wlingi', '82996 Muir Place');
INSERT INTO Locations VALUES ('Gaobu', '3 Northview Circle');
INSERT INTO Locations VALUES ('Tangalla', '24 Manley Pass');
INSERT INTO Locations VALUES ('Daejeon', '328 Schmedeman Terrace');
INSERT INTO Locations VALUES ('Växjö', '784 Duke Place');
INSERT INTO Locations VALUES ('Quankou', '7 Larry Terrace');
INSERT INTO Locations VALUES ('Quintã', '88767 Warner Plaza');
INSERT INTO Locations VALUES ('Zel’va', '5446 Rowland Park');
INSERT INTO Locations VALUES ('Mata-Utu', '0577 Merry Street');
INSERT INTO Locations VALUES ('Luže', '03 Di Loreto Way');
INSERT INTO Locations VALUES ('Nankun', '1 Banding Road');
INSERT INTO Locations VALUES ('Chōfugaoka', '9088 Westridge Center');
INSERT INTO Locations VALUES ('Gowa', '5736 Talmadge Crossing');
INSERT INTO Locations VALUES ('Conceição do Jacuípe', '68157 Daystar Court');
INSERT INTO Locations VALUES ('Kalchevaya', '9 Delladonna Center');
INSERT INTO Locations VALUES ('Paloh', '85 Cardinal Place');
INSERT INTO Locations VALUES ('Talu', '0 Florence Court');
INSERT INTO Locations VALUES ('Xiaxindian', '5760 Portage Plaza');
INSERT INTO Locations VALUES ('Dortmund', '67 Carioca Way');
INSERT INTO Locations VALUES ('Manūjān', '85528 Oriole Pass');
INSERT INTO Locations VALUES ('Shajing', '788 Pleasure Circle');
INSERT INTO Locations VALUES ('Xiumei', '00075 Hansons Court');
INSERT INTO Locations VALUES ('Tambura', '6 Melody Drive');
INSERT INTO Locations VALUES ('Corredoura', '0352 Muir Pass');
INSERT INTO Locations VALUES ('Fort-de-France', '669 Rusk Alley');
INSERT INTO Locations VALUES ('Litian', '610 Hoffman Parkway');
INSERT INTO Locations VALUES ('Kalapagenep', '48756 Dunning Place');
INSERT INTO Locations VALUES ('Bang Bo', '019 Manufacturers Center');
INSERT INTO Locations VALUES ('Zhongxiao', '09602 Portage Drive');
INSERT INTO Locations VALUES ('La Asunción', '170 Stephen Circle');
INSERT INTO Locations VALUES ('Dvurechensk', '67 Duke Drive');
INSERT INTO Locations VALUES ('Jingu', '7960 Roxbury Road');
INSERT INTO Locations VALUES ('Tegalrejo', '476 Butterfield Circle');
INSERT INTO Locations VALUES ('Seseng', '58 Golden Leaf Pass');
INSERT INTO Locations VALUES ('Fangfan', '64006 Annamark Trail');
INSERT INTO Locations VALUES ('Novocherkassk', '8145 Crownhardt Alley');
INSERT INTO Locations VALUES ('Old Harbour Bay', '90640 Roth Pass');
INSERT INTO Locations VALUES ('El Marañón', '688 Bobwhite Way');
INSERT INTO Locations VALUES ('Banqiao', '00500 Corben Center');
INSERT INTO Locations VALUES ('Nizhniy Tagil', '7657 Independence Center');
INSERT INTO Locations VALUES ('Aranguren', '9 Corscot Place');
INSERT INTO Locations VALUES ('Chư Ty', '7 Golf Alley');
INSERT INTO Locations VALUES ('Chicago', '3 Bluestem Hill');
INSERT INTO Locations VALUES ('Monticello', '34209 Schlimgen Terrace');
INSERT INTO Locations VALUES ('Yokosuka', '1 Toban Avenue');
INSERT INTO Locations VALUES ('Tangwei', '006 Calypso Road');
INSERT INTO Locations VALUES ('Kalilu', '8 Meadow Vale Pass');
INSERT INTO Locations VALUES ('San Francisco', '30934 Lien Center');
INSERT INTO Locations VALUES ('Besukrejo', '979 Blaine Point');
INSERT INTO Locations VALUES ('Bontang', '639 Bunting Drive');
INSERT INTO Locations VALUES ('Tarsouat', '62 Prairie Rose Crossing');
INSERT INTO Locations VALUES ('Gabaldon', '6718 Waywood Way');
INSERT INTO Locations VALUES ('Mapulo', '0753 School Lane');
INSERT INTO Locations VALUES ('Dadong', '0 Saint Paul Hill');
INSERT INTO Locations VALUES ('Purwokerto', '78 Logan Center');
INSERT INTO Locations VALUES ('Doushan', '7943 3rd Street');
INSERT INTO Locations VALUES ('Aoji-ri', '2 Milwaukee Circle');
INSERT INTO Locations VALUES ('Pereira', '78846 Caliangt Crossing');
INSERT INTO Locations VALUES ('Chwaszczyno', '753 Novick Junction');
INSERT INTO Locations VALUES ('Naryn', '37 Katie Terrace');
INSERT INTO Locations VALUES ('Mascouche', '57 Tennessee Place');
INSERT INTO Locations VALUES ('Xinhua', '0930 Randy Pass');
INSERT INTO Locations VALUES ('Jianjiang', '90 Sachs Drive');
INSERT INTO Locations VALUES ('Dąbrowice', '94113 Eagle Crest Hill');
INSERT INTO Locations VALUES ('Bambari', '6 Ridgeway Court');
INSERT INTO Locations VALUES ('Majengo', '9193 Del Sol Parkway');
INSERT INTO Locations VALUES ('Magnitogorsk', '2 La Follette Alley');
INSERT INTO Locations VALUES ('Modřice', '67 Atwood Street');
INSERT INTO Locations VALUES ('Xinjia', '857 Kennedy Plaza');
INSERT INTO Locations VALUES ('Gongdanglegi Kulon', '1 International Hill');
INSERT INTO Locations VALUES ('Villa María', '70513 Weeping Birch Circle');
INSERT INTO Locations VALUES ('Descalvado', '746 Acker Terrace');
INSERT INTO Locations VALUES ('Kesamben', '5413 Mosinee Center');
INSERT INTO Locations VALUES ('Vahdat', '34977 Westend Court');
INSERT INTO Locations VALUES ('Patrocínio', '80 Buell Court');
INSERT INTO Locations VALUES ('Luodian', '9975 Maywood Parkway');
INSERT INTO Locations VALUES ('Sinarjaya', '970 Dawn Park');
INSERT INTO Locations VALUES ('Kole', '9303 Mockingbird Road');
INSERT INTO Locations VALUES ('Jiefang', '6 Macpherson Drive');
INSERT INTO Locations VALUES ('Misungwi', '0 Dawn Place');
INSERT INTO Locations VALUES ('Miaoya', '86 Pierstorff Way');
INSERT INTO Locations VALUES ('Mbanza Congo', '6881 Independence Alley');
INSERT INTO Locations VALUES ('Orimattila', '0002 Brown Terrace');
INSERT INTO Locations VALUES ('Castelo', '7 Arrowood Drive');
INSERT INTO Locations VALUES ('Kuching', '155 Ilene Road');
INSERT INTO Locations VALUES ('Caibarién', '54 Namekagon Avenue');
INSERT INTO Locations VALUES ('Bali', '91927 West Circle');
INSERT INTO Locations VALUES ('Ferreiras', '28499 Mendota Alley');
INSERT INTO Locations VALUES ('Jiayi', '71 Orin Drive');
INSERT INTO Locations VALUES ('Yingdianjie', '9 Heath Drive');
INSERT INTO Locations VALUES ('Saverne', '4713 Mayer Plaza');
INSERT INTO Locations VALUES ('Ostroměř', '9977 Commercial Junction');
INSERT INTO Locations VALUES ('Pangal Sur', '5928 Corry Parkway');
INSERT INTO Locations VALUES ('Sangmélima', '91313 Northview Center');
INSERT INTO Locations VALUES ('Montgomery', '048 Cordelia Drive');
INSERT INTO Locations VALUES ('Vicente Guerrero', '83 Hagan Lane');
INSERT INTO Locations VALUES ('Prakhon Chai', '0985 Dixon Way');
INSERT INTO Locations VALUES ('Jarinu', '26830 Pleasure Junction');
INSERT INTO Locations VALUES ('Ivatsevichy', '72 Menomonie Park');
INSERT INTO Locations VALUES ('Ballisodare', '1 Bluestem Place');
INSERT INTO Locations VALUES ('Saint Louis', '6074 Mallard Street');
INSERT INTO Locations VALUES ('Motygino', '4808 Almo Lane');
INSERT INTO Locations VALUES ('Darkovice', '0 Red Cloud Way');
INSERT INTO Locations VALUES ('Milicz', '49586 Luster Center');
INSERT INTO Locations VALUES ('Anjihai', '66841 Claremont Hill');
INSERT INTO Locations VALUES ('Jakubowice Murowane', '510 Hanover Terrace');
INSERT INTO Locations VALUES ('Zhoushizhuang', '6 Derek Hill');
INSERT INTO Locations VALUES ('Canta', '93 Grayhawk Parkway');
INSERT INTO Locations VALUES ('Töreboda', '1 Rowland Terrace');
INSERT INTO Locations VALUES ('Alingsås', '1 Stephen Plaza');
INSERT INTO Locations VALUES ('Gampingan', '39 Northridge Park');
INSERT INTO Locations VALUES ('Kristianstad', '8 Fair Oaks Hill');
INSERT INTO Locations VALUES ('Balengbeng', '6 Jenifer Terrace');
INSERT INTO Locations VALUES ('Bužim', '50 Kennedy Junction');
INSERT INTO Locations VALUES ('Yelenendorf', '48 Stone Corner Trail');
INSERT INTO Locations VALUES ('Yangp''yŏng', '660 Carberry Hill');
INSERT INTO Locations VALUES ('Kecskemét', '48009 Oriole Place');
INSERT INTO Locations VALUES ('Brylivka', '0319 Pepper Wood Lane');
INSERT INTO Locations VALUES ('Sōka', '95802 Ridgeway Lane');
INSERT INTO Locations VALUES ('Lusk', '278 Trailsway Drive');
INSERT INTO Locations VALUES ('Mingyu', '31568 Cardinal Way');
INSERT INTO Locations VALUES ('Sotnikovskoye', '96 Randy Hill');
INSERT INTO Locations VALUES ('Barretos', '31 Golf Crossing');
INSERT INTO Locations VALUES ('Barusuda', '00356 Gina Hill');
INSERT INTO Locations VALUES ('Oleszyce', '0333 Clove Pass');
INSERT INTO Locations VALUES ('Stockholm', '7723 American Ash Center');
INSERT INTO Locations VALUES ('San Bernardino', '5 Onsgard Avenue');
INSERT INTO Locations VALUES ('Zainsk', '18030 Bay Drive');
INSERT INTO Locations VALUES ('Khánh Hải', '30 Spohn Road');
INSERT INTO Locations VALUES ('Yanfolila', '1986 Schmedeman Place');
INSERT INTO Locations VALUES ('Lanckorona', '456 Continental Street');
INSERT INTO Locations VALUES ('Busia', '0 Commercial Pass');
INSERT INTO Locations VALUES ('Irahuan', '3804 Forest Terrace');
INSERT INTO Locations VALUES ('Gobernador Costa', '7 New Castle Road');
INSERT INTO Locations VALUES ('Uppsala', '95973 Laurel Parkway');
INSERT INTO Locations VALUES ('Khairpur', '8880 Dunning Lane');
INSERT INTO Locations VALUES ('Tiandu', '3 Messerschmidt Street');
INSERT INTO Locations VALUES ('Cockburn Town', '065 Golf View Terrace');
INSERT INTO Locations VALUES ('Kadudampit', '93 Sheridan Alley');
INSERT INTO Locations VALUES ('Kumba', '20772 Westport Trail');
INSERT INTO Locations VALUES ('Songkeng', '112 Pleasure Avenue');
INSERT INTO Locations VALUES ('Montaneza', '0644 Bayside Junction');
INSERT INTO Locations VALUES ('Ad Dimnah', '84238 Upham Street');
INSERT INTO Locations VALUES ('Neos Voutzás', '4 Lighthouse Bay Trail');
INSERT INTO Locations VALUES ('Belfast', '49 Corry Lane');
INSERT INTO Locations VALUES ('Manchioneal', '1 Cody Terrace');
INSERT INTO Locations VALUES ('Vis', '8 Hansons Trail');
INSERT INTO Locations VALUES ('Guder', '12 Northport Parkway');
INSERT INTO Locations VALUES ('Kozhevnikovo', '227 Randy Street');
INSERT INTO Locations VALUES ('Verkhoshizhem’ye', '90 Holy Cross Way');
INSERT INTO Locations VALUES ('Yiyang', '3 Warbler Drive');
INSERT INTO Locations VALUES ('Jejkowice', '19434 Shasta Junction');
INSERT INTO Locations VALUES ('Velestíno', '26929 Ohio Center');
INSERT INTO Locations VALUES ('Rennes', '433 Steensland Plaza');
INSERT INTO Locations VALUES ('Saint-Augustin', '02 Swallow Terrace');
INSERT INTO Locations VALUES ('Zhonghechang', '7 Trailsway Way');
INSERT INTO Locations VALUES ('Apt', '39861 Alpine Way');
INSERT INTO Locations VALUES ('Banī Walīd', '4965 Cherokee Circle');
INSERT INTO Locations VALUES ('Le Puy-en-Velay', '07 Westridge Terrace');
INSERT INTO Locations VALUES ('Sukamenak', '97 Mayfield Plaza');
INSERT INTO Locations VALUES ('Nadrupe', '09 Goodland Road');
INSERT INTO Locations VALUES ('Hoboksar', '7 Elgar Point');
INSERT INTO Locations VALUES ('Pereyaslav-Khmel’nyts’kyy', '4 Roxbury Parkway');
INSERT INTO Locations VALUES ('Jubao', '73714 2nd Parkway');
INSERT INTO Locations VALUES ('Pekan', '32 Leroy Park');
INSERT INTO Locations VALUES ('Conselheiro Lafaiete', '6 Oneill Place');
INSERT INTO Locations VALUES ('Senj', '7136 Hanover Way');
INSERT INTO Locations VALUES ('Sayansk', '8 Karstens Street');
INSERT INTO Locations VALUES ('Káto Dhiminió', '2911 Kenwood Parkway');
INSERT INTO Locations VALUES ('Paço', '36 Grim Parkway');
INSERT INTO Locations VALUES ('Bahaodi', '09306 Ridgeway Circle');
INSERT INTO Locations VALUES ('Antang', '6 3rd Road');
INSERT INTO Locations VALUES ('Margotuhu Kidul', '62129 Kedzie Place');
INSERT INTO Locations VALUES ('Montgomery', '767 Arkansas Drive');
INSERT INTO Locations VALUES ('Rokietnica', '3 Lake View Lane');
INSERT INTO Locations VALUES ('Teberda', '72588 Kensington Point');
INSERT INTO Locations VALUES ('Nanxinxiang', '69914 Saint Paul Plaza');
INSERT INTO Locations VALUES ('Järvakandi', '1 Crescent Oaks Drive');
INSERT INTO Locations VALUES ('Sandaoba', '95827 Norway Maple Avenue');
INSERT INTO Locations VALUES ('Nueve de Julio', '0454 Stone Corner Avenue');
INSERT INTO Locations VALUES ('Quimilí', '99 Vera Crossing');
INSERT INTO Locations VALUES ('Semey', '7 Lien Parkway');
INSERT INTO Locations VALUES ('‘Ūrīf', '447 Dexter Circle');
INSERT INTO Locations VALUES ('Karangan', '62 Hanover Point');
INSERT INTO Locations VALUES ('Faqīrwāli', '6 Kinsman Place');
INSERT INTO Locations VALUES ('Đoan Hùng', '6197 Almo Drive');
INSERT INTO Locations VALUES ('Changuinola', '8 Morning Lane');
INSERT INTO Locations VALUES ('Jiru', '99609 Katie Street');
INSERT INTO Locations VALUES ('Manwakh', '6 Boyd Avenue');
INSERT INTO Locations VALUES ('Dulles', '9449 Michigan Center');
INSERT INTO Locations VALUES ('Hongsi', '58 Utah Park');
INSERT INTO Locations VALUES ('Ciburial', '5 Grim Hill');
INSERT INTO Locations VALUES ('Leidschendam', '85 Forster Crossing');
INSERT INTO Locations VALUES ('Kárystos', '75991 Harper Place');
INSERT INTO Locations VALUES ('Setro', '75 Tennyson Plaza');
INSERT INTO Locations VALUES ('Svilajnac', '30399 Doe Crossing Lane');
INSERT INTO Locations VALUES ('La Cañada', '7 Charing Cross Avenue');
INSERT INTO Locations VALUES ('Perpignan', '51 Kedzie Circle');
INSERT INTO Locations VALUES ('Ucluelet', '092 Memorial Point');
INSERT INTO Locations VALUES ('Parral', '36 Fulton Point');
INSERT INTO Locations VALUES ('Cigadog', '35546 Jenna Terrace');
INSERT INTO Locations VALUES ('Gualán', '04225 Pawling Avenue');
INSERT INTO Locations VALUES ('Alençon', '966 Sommers Lane');
INSERT INTO Locations VALUES ('Girardot', '15 Roxbury Junction');
INSERT INTO Locations VALUES ('Merton', '37305 Golf Course Way');
INSERT INTO Locations VALUES ('Medalem', '8253 Hallows Center');
INSERT INTO Locations VALUES ('Xiachu', '8078 Dixon Parkway');
INSERT INTO Locations VALUES ('La Sarre', '05841 Blaine Parkway');
INSERT INTO Locations VALUES ('Huamali', '30 Di Loreto Street');
INSERT INTO Locations VALUES ('Al Miftāḩ', '6 Anhalt Alley');
INSERT INTO Locations VALUES ('Munse', '77799 Dwight Court');
INSERT INTO Locations VALUES ('Rabat', '71 Burrows Lane');
INSERT INTO Locations VALUES ('Kopidlno', '09296 Maywood Way');
INSERT INTO Locations VALUES ('Pangkalan', '57737 Scott Street');
INSERT INTO Locations VALUES ('Góra Kalwaria', '976 Esch Way');
INSERT INTO Locations VALUES ('Buchlovice', '8 North Hill');
INSERT INTO Locations VALUES ('Gitega', '69 Emmet Plaza');
INSERT INTO Locations VALUES ('Qishn', '67616 Nancy Plaza');
INSERT INTO Locations VALUES ('Mesker-Yurt', '98161 Bellgrove Avenue');
INSERT INTO Locations VALUES ('Jaru', '5606 Vermont Pass');
INSERT INTO Locations VALUES ('Harbutowice', '18 Blackbird Center');
INSERT INTO Locations VALUES ('Sułoszowa', '41472 Quincy Road');
INSERT INTO Locations VALUES ('Mangai', '0 Meadow Ridge Junction');
INSERT INTO Locations VALUES ('Zuobude', '03527 Northwestern Alley');
INSERT INTO Locations VALUES ('Nong Khai', '94012 5th Avenue');
INSERT INTO Locations VALUES ('Žrnovnica', '8 Loftsgordon Hill');
INSERT INTO Locations VALUES ('Nālūt', '26 Tennyson Circle');
INSERT INTO Locations VALUES ('São Pedro', '406 Stang Circle');
INSERT INTO Locations VALUES ('Anáfi', '750 Ludington Avenue');
INSERT INTO Locations VALUES ('Dayou', '00794 Amoth Plaza');
INSERT INTO Locations VALUES ('Kīevka', '8654 Butternut Place');
INSERT INTO Locations VALUES ('Baikouquan', '264 Bluejay Alley');
INSERT INTO Locations VALUES ('Xagqu', '365 Green Point');
INSERT INTO Locations VALUES ('Kalipare', '87699 Dovetail Street');
INSERT INTO Locations VALUES ('Ubrub', '16 Morning Avenue');
INSERT INTO Locations VALUES ('Jingtou', '467 Northland Place');
INSERT INTO Locations VALUES ('Ash Shiḩr', '5088 Fairview Plaza');
INSERT INTO Locations VALUES ('Köln', '28 Arizona Pass');
INSERT INTO Locations VALUES ('Pionerskiy', '15883 Fallview Trail');
INSERT INTO Locations VALUES ('Ra-ngae', '355 Anthes Park');
INSERT INTO Locations VALUES ('Järfälla', '8477 Columbus Crossing');
INSERT INTO Locations VALUES ('Toledo', '720 Mccormick Court');
INSERT INTO Locations VALUES ('Huangbu', '64 Mallard Hill');
INSERT INTO Locations VALUES ('Askaniya Nova', '2853 Kingsford Pass');
INSERT INTO Locations VALUES ('Ampara', '1223 Erie Park');
INSERT INTO Locations VALUES ('Ajaccio', '5159 Dunning Pass');
INSERT INTO Locations VALUES ('Rambouillet', '74823 Columbus Way');
INSERT INTO Locations VALUES ('Baimangpu', '62 Manitowish Plaza');
INSERT INTO Locations VALUES ('Xixiang', '418 Vernon Drive');
INSERT INTO Locations VALUES ('Jiaoqiao', '65 Forest Terrace');
INSERT INTO Locations VALUES ('Jiazhuyuan', '66258 Pearson Center');
INSERT INTO Locations VALUES ('El Pino', '90186 Arizona Park');
INSERT INTO Locations VALUES ('Sundbyberg', '816 Grasskamp Terrace');
INSERT INTO Locations VALUES ('Al Ḩīlah', '21600 Golden Leaf Way');
INSERT INTO Locations VALUES ('Korfovskiy', '5 Maple Avenue');
INSERT INTO Locations VALUES ('Aboisso', '29367 Pawling Trail');
INSERT INTO Locations VALUES ('Dniprodzerzhyns’k', '27 Garrison Terrace');
INSERT INTO Locations VALUES ('Moa', '630 Springs Avenue');
INSERT INTO Locations VALUES ('Novyy Oskol', '31 Declaration Center');
INSERT INTO Locations VALUES ('Caucagüito', '3067 Debs Point');
INSERT INTO Locations VALUES ('Riyue', '3 6th Plaza');
INSERT INTO Locations VALUES ('Chenggang', '2 Scofield Place');
INSERT INTO Locations VALUES ('Church End', '9941 Merrick Park');
INSERT INTO Locations VALUES ('Lijie', '38 Bowman Court');
INSERT INTO Locations VALUES ('Dachong', '81633 Dovetail Road');
INSERT INTO Locations VALUES ('Sao Hai', '25376 Basil Pass');
INSERT INTO Locations VALUES ('Kuanchuan', '9822 Troy Road');
INSERT INTO Locations VALUES ('Butere', '72266 Fremont Street');
INSERT INTO Locations VALUES ('El Ksour', '04077 Hollow Ridge Street');
INSERT INTO Locations VALUES ('Évreux', '7358 Surrey Court');
INSERT INTO Locations VALUES ('Massaranduba', '15671 Mallard Center');
INSERT INTO Locations VALUES ('Novyy Svit', '27 Hoard Avenue');
INSERT INTO Locations VALUES ('Telhado', '6173 Schlimgen Lane');
INSERT INTO Locations VALUES ('Inta', '552 Green Plaza');
INSERT INTO Locations VALUES ('Lilongwe', '2 Green Ridge Street');
INSERT INTO Locations VALUES ('Quintong', '58521 Delaware Avenue');
INSERT INTO Locations VALUES ('Tegallega', '6156 Del Sol Drive');
INSERT INTO Locations VALUES ('Ipaba', '74 Homewood Street');
INSERT INTO Locations VALUES ('Xiapu', '93123 Ohio Avenue');
INSERT INTO Locations VALUES ('Jutaí', '73682 Marcy Road');
INSERT INTO Locations VALUES ('Tanagara', '3811 Mcguire Plaza');
INSERT INTO Locations VALUES ('Brikama Nding', '2 Vermont Park');
INSERT INTO Locations VALUES ('Tuburan', '808 Northfield Street');
INSERT INTO Locations VALUES ('São Domingos do Maranhão', '634 Green Plaza');
INSERT INTO Locations VALUES ('Aguas Corrientes', '9 Brown Lane');
INSERT INTO Locations VALUES ('Priekule', '5684 Reinke Hill');
INSERT INTO Locations VALUES ('Chone', '5 Forster Trail');
INSERT INTO Locations VALUES ('Pagnag', '6808 Petterle Road');
INSERT INTO Locations VALUES ('Xinji', '68 Jenna Lane');
INSERT INTO Locations VALUES ('Sendai-shi', '6 Del Sol Point');
INSERT INTO Locations VALUES ('Santol', '9211 Riverside Way');
INSERT INTO Locations VALUES ('Padre Nabeto', '512 Russell Road');
INSERT INTO Locations VALUES ('Savran’', '1 Acker Court');
INSERT INTO Locations VALUES ('Morcellemont Saint André', '6113 Kensington Point');
INSERT INTO Locations VALUES ('Yinying', '22489 Monument Trail');
INSERT INTO Locations VALUES ('Berëzovyy', '00 East Avenue');
INSERT INTO Locations VALUES ('Zhuxi', '86750 Porter Plaza');
INSERT INTO Locations VALUES ('Gareba', '4 Maple Wood Hill');
INSERT INTO Locations VALUES ('Kashirskoye', '20305 Marcy Court');
INSERT INTO Locations VALUES ('Oslo', '4 Luster Pass');
INSERT INTO Locations VALUES ('Tabora', '7405 Fulton Place');
INSERT INTO Locations VALUES ('Vänersborg', '65 Southridge Hill');
INSERT INTO Locations VALUES ('Khvastovichi', '8 Red Cloud Plaza');
INSERT INTO Locations VALUES ('San Pedro Carchá', '18720 Stoughton Hill');
INSERT INTO Locations VALUES ('Zhuqi', '77746 Independence Crossing');
INSERT INTO Locations VALUES ('Ambam', '49412 Ronald Regan Parkway');
INSERT INTO Locations VALUES ('Xiluo', '679 Quincy Drive');
INSERT INTO Locations VALUES ('Khirdalan', '8 Bunting Hill');
INSERT INTO Locations VALUES ('Piracuruca', '2 Haas Road');
INSERT INTO Locations VALUES ('Coronel Vivida', '45055 Dwight Lane');
INSERT INTO Locations VALUES ('Velký Újezd', '65953 Scott Place');
INSERT INTO Locations VALUES ('Pustomyty', '9 Porter Hill');
INSERT INTO Locations VALUES ('Władysławowo', '81 Independence Circle');
INSERT INTO Locations VALUES ('Xuefu', '47 Donald Crossing');
INSERT INTO Locations VALUES ('Zhujiatai', '04931 Katie Place');
INSERT INTO Locations VALUES ('Nijmegen', '74 Bultman Park');
INSERT INTO Locations VALUES ('Huxi', '7 1st Lane');
INSERT INTO Locations VALUES ('Puerto Quellón', '8299 Corben Trail');
INSERT INTO Locations VALUES ('Selebi-Phikwe', '667 Kedzie Junction');
INSERT INTO Locations VALUES ('Remolino', '81379 Miller Pass');
INSERT INTO Locations VALUES ('Eséka', '62831 Ryan Alley');
INSERT INTO Locations VALUES ('Malin', '62629 Independence Plaza');
INSERT INTO Locations VALUES ('Kogon', '203 Eastlawn Pass');
INSERT INTO Locations VALUES ('Luzino', '0046 Algoma Lane');
INSERT INTO Locations VALUES ('Rambouillet', '90083 Homewood Pass');
INSERT INTO Locations VALUES ('Mosquera', '44 Talisman Alley');
INSERT INTO Locations VALUES ('Gedian', '357 Graedel Alley');
INSERT INTO Locations VALUES ('Chixi', '131 Oak Valley Alley');
INSERT INTO Locations VALUES ('Yaring', '9887 Northview Junction');
INSERT INTO Locations VALUES ('Ternate', '72428 Aberg Circle');
INSERT INTO Locations VALUES ('Krapina', '81 Old Gate Hill');
INSERT INTO Locations VALUES ('Shangyang', '1 Chive Trail');
INSERT INTO Locations VALUES ('Mambi', '8697 Truax Junction');
INSERT INTO Locations VALUES ('Satu Nou', '7731 Kenwood Alley');
INSERT INTO Locations VALUES ('Baojiadian', '9 Del Mar Center');
INSERT INTO Locations VALUES ('Lugui', '98952 Prentice Avenue');
INSERT INTO Locations VALUES ('Komaki', '3282 Linden Road');
INSERT INTO Locations VALUES ('Xitou', '1 Ridgeway Avenue');
INSERT INTO Locations VALUES ('Babana', '1510 Heath Center');
INSERT INTO Locations VALUES ('Krajan Gajahmati', '39586 Onsgard Place');
INSERT INTO Locations VALUES ('Tanuma', '1 Thompson Drive');
INSERT INTO Locations VALUES ('San José', '7 Columbus Terrace');
INSERT INTO Locations VALUES ('Sete Lagoas', '53 North Park');
INSERT INTO Locations VALUES ('Tyukalinsk', '206 Jenifer Drive');
INSERT INTO Locations VALUES ('Burgas', '169 Marcy Alley');
INSERT INTO Locations VALUES ('Paradela', '4 Linden Circle');
INSERT INTO Locations VALUES ('Cashel', '9651 Meadow Vale Court');
INSERT INTO Locations VALUES ('Kurów', '28705 East Center');
INSERT INTO Locations VALUES ('South River', '3639 Sugar Park');
INSERT INTO Locations VALUES ('Votkinsk', '257 Heffernan Alley');
INSERT INTO Locations VALUES ('Stockholm', '60566 Green Park');
INSERT INTO Locations VALUES ('Wassu', '31868 Vermont Court');
INSERT INTO Locations VALUES ('Motala', '2716 Lerdahl Parkway');
INSERT INTO Locations VALUES ('Igarapé', '33026 Basil Trail');
INSERT INTO Locations VALUES ('Voznesen’ye', '9027 Shelley Drive');
INSERT INTO Locations VALUES ('La Laguna', '755 Graceland Way');
INSERT INTO Locations VALUES ('Suchedniów', '46473 Ohio Circle');
INSERT INTO Locations VALUES ('Vilque Chico', '990 Cardinal Drive');
INSERT INTO Locations VALUES ('Las Palmas', '5 Ilene Parkway');
INSERT INTO Locations VALUES ('Bandung', '18290 Pleasure Avenue');
INSERT INTO Locations VALUES ('Napu', '0543 Division Lane');
INSERT INTO Locations VALUES ('Santiago de Cao', '7 Holy Cross Street');
INSERT INTO Locations VALUES ('Astghadzor', '13453 Anzinger Road');
INSERT INTO Locations VALUES ('Chugay', '5 Monterey Center');
INSERT INTO Locations VALUES ('Kuštilj', '2 Milwaukee Avenue');
INSERT INTO Locations VALUES ('Bystré', '25205 American Ash Avenue');
INSERT INTO Locations VALUES ('Maripipi', '1 Amoth Pass');
INSERT INTO Locations VALUES ('Girona', '7 Sycamore Way');
INSERT INTO Locations VALUES ('Yanglinshi', '1 Oak Valley Place');
INSERT INTO Locations VALUES ('Kobuleti', '84 Morningstar Street');
INSERT INTO Locations VALUES ('Banga', '8 Cottonwood Park');
INSERT INTO Locations VALUES ('Badian', '05 Judy Parkway');
INSERT INTO Locations VALUES ('Suvorovo', '7 Tomscot Parkway');
INSERT INTO Locations VALUES ('Riobamba', '1211 6th Place');
INSERT INTO Locations VALUES ('Mpika', '19194 Maryland Crossing');
INSERT INTO Locations VALUES ('Huaquirca', '237 Independence Hill');
INSERT INTO Locations VALUES ('Monte Aprazível', '2 Comanche Parkway');
INSERT INTO Locations VALUES ('Effium', '46568 Florence Avenue');
INSERT INTO Locations VALUES ('Mairiporã', '528 Kim Alley');
INSERT INTO Locations VALUES ('Homa Bay', '2 Laurel Plaza');
INSERT INTO Locations VALUES ('Ålesund', '45855 Birchwood Place');
INSERT INTO Locations VALUES ('Hedaru', '112 Dryden Road');
INSERT INTO Locations VALUES ('Piasek', '8 East Point');
INSERT INTO Locations VALUES ('João Câmara', '2937 Melvin Parkway');
INSERT INTO Locations VALUES ('Guadalupe Victoria', '86 Oak Valley Alley');
INSERT INTO Locations VALUES ('Caminauit', '20867 Erie Terrace');
INSERT INTO Locations VALUES ('Selikhino', '6 Rowland Crossing');
INSERT INTO Locations VALUES ('Novohrad-Volyns’kyy', '170 Straubel Drive');
INSERT INTO Locations VALUES ('New York City', '6882 Crescent Oaks Terrace');
INSERT INTO Locations VALUES ('Piekielnik', '3591 Roth Way');
INSERT INTO Locations VALUES ('Xihongmen', '2068 Nobel Drive');
INSERT INTO Locations VALUES ('Huangling', '77106 Fordem Way');
INSERT INTO Locations VALUES ('Tirhanimîne', '276 Scott Alley');
INSERT INTO Locations VALUES ('Tsotsin-Yurt', '695 Haas Center');
INSERT INTO Locations VALUES ('Foxrock', '93246 Colorado Court');
INSERT INTO Locations VALUES ('Lin’an', '51 David Plaza');
INSERT INTO Locations VALUES ('Kinalansan', '3089 7th Pass');
INSERT INTO Locations VALUES ('Chuntai', '95555 Village Avenue');
INSERT INTO Locations VALUES ('Jingling', '760 Amoth Crossing');
INSERT INTO Locations VALUES ('Candelaria', '3407 Bayside Lane');
INSERT INTO Locations VALUES ('Totness', '8 Maple Avenue');
INSERT INTO Locations VALUES ('Aragarças', '19 Fulton Terrace');
INSERT INTO Locations VALUES ('Jadów', '19272 Vernon Way');
INSERT INTO Locations VALUES ('Siedlce', '869 Mockingbird Crossing');
INSERT INTO Locations VALUES ('Zushi', '7 Welch Pass');
INSERT INTO Locations VALUES ('Utarapasar', '711 Buhler Hill');
INSERT INTO Locations VALUES ('Waiwukak', '8 Autumn Leaf Lane');
INSERT INTO Locations VALUES ('Setono', '25572 Graceland Avenue');
INSERT INTO Locations VALUES ('Stockholm', '34378 Valley Edge Drive');
INSERT INTO Locations VALUES ('Wiesbaden', '10184 Hagan Place');
INSERT INTO Locations VALUES ('Złotoryja', '51 Summer Ridge Junction');
INSERT INTO Locations VALUES ('Lazaro Cardenas', '201 Anhalt Street');
INSERT INTO Locations VALUES ('Göteborg', '2 Pepper Wood Court');
INSERT INTO Locations VALUES ('Petare', '1239 Londonderry Drive');
INSERT INTO Locations VALUES ('Kakegawa', '3206 Buena Vista Crossing');
INSERT INTO Locations VALUES ('Xiamujiao', '562 Division Way');
INSERT INTO Locations VALUES ('North Bay', '4 Sage Street');
INSERT INTO Locations VALUES ('Centurion', '8095 Springs Drive');
INSERT INTO Locations VALUES ('Rote', '0 Bluestem Place');
INSERT INTO Locations VALUES ('Tangjiakou', '09 Judy Court');
INSERT INTO Locations VALUES ('Shuanglu', '66378 Hansons Alley');
INSERT INTO Locations VALUES ('Nang Rong', '8327 Starling Alley');
INSERT INTO Locations VALUES ('Baraçais', '4 Heffernan Terrace');
INSERT INTO Locations VALUES ('Lucma', '75769 Nobel Alley');
INSERT INTO Locations VALUES ('Sindangrasa', '8 Comanche Road');
INSERT INTO Locations VALUES ('Fanrong', '52552 Independence Alley');
INSERT INTO Locations VALUES ('HanHuang', '7 Merrick Place');
INSERT INTO Locations VALUES ('Gaza', '09260 Iowa Terrace');
INSERT INTO Locations VALUES ('Xiangrong', '7912 Hayes Place');
INSERT INTO Locations VALUES ('Gulu', '472 Barby Road');
INSERT INTO Locations VALUES ('Évry', '51721 Northridge Center');
INSERT INTO Locations VALUES ('Liaodian', '193 Packers Park');
INSERT INTO Locations VALUES ('Nilanapo', '70 Cascade Drive');
INSERT INTO Locations VALUES ('Harar', '7600 Boyd Park');
INSERT INTO Locations VALUES ('Miaogou', '67 Vera Road');
INSERT INTO Locations VALUES ('Ergates', '04316 Lake View Pass');
INSERT INTO Locations VALUES ('Norrköping', '85791 Anderson Trail');
INSERT INTO Locations VALUES ('Pardubice', '42931 Cascade Way');
INSERT INTO Locations VALUES ('Charopó', '79736 Grover Alley');
INSERT INTO Locations VALUES ('Limon', '44 Westerfield Crossing');
INSERT INTO Locations VALUES ('Kitāf', '796 Shopko Point');
INSERT INTO Locations VALUES ('Wuluo', '6 Warbler Pass');
INSERT INTO Locations VALUES ('Bugcaon', '0150 Hagan Pass');
INSERT INTO Locations VALUES ('Cravo Norte', '9 Grasskamp Street');
INSERT INTO Locations VALUES ('Huixian Chengguanzhen', '0 Stone Corner Place');
INSERT INTO Locations VALUES ('Örebro', '316 Fuller Avenue');
INSERT INTO Locations VALUES ('São Leopoldo', '5 Hallows Road');
INSERT INTO Locations VALUES ('Shwebo', '8 Briar Crest Street');
INSERT INTO Locations VALUES ('Srunikrajan', '16731 Russell Road');
INSERT INTO Locations VALUES ('Novoshakhtinsk', '689 Oneill Parkway');
INSERT INTO Locations VALUES ('Belišće', '145 David Terrace');
INSERT INTO Locations VALUES ('Envigado', '2917 Utah Road');
INSERT INTO Locations VALUES ('Jiaoxie', '60793 Spenser Street');
INSERT INTO Locations VALUES ('Shishan', '8521 Stone Corner Terrace');
INSERT INTO Locations VALUES ('Dresi Wetan', '35059 Morning Lane');
INSERT INTO Locations VALUES ('Beaverton', '03 Kings Terrace');
INSERT INTO Locations VALUES ('Pemex', '1689 Golden Leaf Point');
INSERT INTO Locations VALUES ('Madamba', '92216 Eagan Road');
INSERT INTO Locations VALUES ('Guanta', '6 Moland Junction');
INSERT INTO Locations VALUES ('Huangbu', '51824 Merrick Circle');
INSERT INTO Locations VALUES ('Cikadondongdesa', '88522 Manufacturers Court');
INSERT INTO Locations VALUES ('Oshnavīyeh', '6 Heffernan Avenue');
INSERT INTO Locations VALUES ('Chidian', '181 Oak Valley Road');
INSERT INTO Locations VALUES ('Porangaba', '3625 Main Road');
INSERT INTO Locations VALUES ('Kalampáka', '2 Haas Plaza');
INSERT INTO Locations VALUES ('Leran Wetan', '79 Superior Circle');
INSERT INTO Locations VALUES ('Arnhem', '1 Jana Drive');
INSERT INTO Locations VALUES ('Dolní Počernice', '3361 Lunder Way');
INSERT INTO Locations VALUES ('Namyangju', '43 Kensington Junction');
INSERT INTO Locations VALUES ('Centro Habana', '2591 Nevada Place');
INSERT INTO Locations VALUES ('Verkhniy Lomov', '557 Helena Hill');
INSERT INTO Locations VALUES ('Huangpu', '53 Reinke Trail');
INSERT INTO Locations VALUES ('Hrádek', '5 Clove Pass');
INSERT INTO Locations VALUES ('Zimovniki', '03418 Buhler Avenue');
INSERT INTO Locations VALUES ('Bergen op Zoom', '791 Shasta Road');
INSERT INTO Locations VALUES ('Xiaoruo', '6 Banding Terrace');
INSERT INTO Locations VALUES ('Alcácer do Sal', '5 Vernon Alley');
INSERT INTO Locations VALUES ('Ḩakamā', '6244 Gerald Way');
INSERT INTO Locations VALUES ('Lubasz', '213 Northwestern Plaza');
INSERT INTO Locations VALUES ('Erniusuokou', '94 Pleasure Hill');
INSERT INTO Locations VALUES ('Mekarsari', '40680 Pierstorff Avenue');
INSERT INTO Locations VALUES ('Kemlya', '26 Lindbergh Terrace');
INSERT INTO Locations VALUES ('El Puerto', '4 Hudson Alley');
INSERT INTO Locations VALUES ('Dengyue', '86861 Melby Point');
INSERT INTO Locations VALUES ('Guaratinguetá', '306 Crowley Road');
INSERT INTO Locations VALUES ('Kumla', '41 Clemons Circle');
INSERT INTO Locations VALUES ('Firmat', '6802 Atwood Park');
INSERT INTO Locations VALUES ('Zaymishche', '2 Continental Avenue');
INSERT INTO Locations VALUES ('Jiayi', '00851 Pennsylvania Avenue');
INSERT INTO Locations VALUES ('Nizhniy Chir', '86 Mosinee Avenue');
INSERT INTO Locations VALUES ('Xiaojie', '51447 Shoshone Circle');
INSERT INTO Locations VALUES ('Berlin', '84 Ridgeway Hill');
INSERT INTO Locations VALUES ('Angers', '7919 Ilene Trail');
INSERT INTO Locations VALUES ('Aki', '728 Schiller Avenue');
INSERT INTO Locations VALUES ('Lodja', '522 Golf Course Court');
INSERT INTO Locations VALUES ('Lambton Shores', '47956 Sycamore Center');
INSERT INTO Locations VALUES ('Lisewo Malborskie', '3069 Anhalt Plaza');
INSERT INTO Locations VALUES ('Corpus Christi', '38 Corry Crossing');
INSERT INTO Locations VALUES ('Lyuban’', '420 Kedzie Hill');
INSERT INTO Locations VALUES ('Kuripan', '55 Everett Plaza');
INSERT INTO Locations VALUES ('Gračec', '066 Doe Crossing Crossing');
INSERT INTO Locations VALUES ('Kaédi', '64 Hovde Court');
INSERT INTO Locations VALUES ('Hanting', '11106 Dixon Trail');
INSERT INTO Locations VALUES ('Heping', '6155 Forster Park');
INSERT INTO Locations VALUES ('Mlaka pri Kranju', '2439 Brickson Park Junction');
INSERT INTO Locations VALUES ('Novouzensk', '908 Sommers Drive');
INSERT INTO Locations VALUES ('Aipe', '7 Anhalt Center');
INSERT INTO Locations VALUES ('Obispos', '36 Linden Junction');
INSERT INTO Locations VALUES ('Fundación', '96010 Barnett Lane');
INSERT INTO Locations VALUES ('Darłowo', '08 Dapin Lane');
INSERT INTO Locations VALUES ('Molchanovo', '7832 Prentice Terrace');
INSERT INTO Locations VALUES ('Krajan Satu', '1 Lien Way');
INSERT INTO Locations VALUES ('Cahuacho', '5821 Mcbride Park');
INSERT INTO Locations VALUES ('Oxelösund', '8534 Burrows Center');
INSERT INTO Locations VALUES ('Xinkaikou', '2597 Towne Plaza');
INSERT INTO Locations VALUES ('Ponta Grossa', '633 Continental Center');
INSERT INTO Locations VALUES ('Bahir Dar', '2432 Marcy Plaza');
INSERT INTO Locations VALUES ('Mpraeso', '8440 Arrowood Point');
INSERT INTO Locations VALUES ('Banho e Carvalhosa', '14645 Roth Alley');
INSERT INTO Locations VALUES ('Sibulan', '7237 Gateway Park');
INSERT INTO Locations VALUES ('Hrotovice', '77053 Ridgeway Junction');
INSERT INTO Locations VALUES ('Mainz', '900 Northland Street');
INSERT INTO Locations VALUES ('Karakabak', '5252 Everett Way');
INSERT INTO Locations VALUES ('Shinkafe', '35 Arizona Crossing');
INSERT INTO Locations VALUES ('Nanyang', '31 7th Road');
INSERT INTO Locations VALUES ('Bangrat', '1 Spenser Lane');
INSERT INTO Locations VALUES ('Baiquesi', '332 Lukken Court');
INSERT INTO Locations VALUES ('Bayan Tuohai', '2504 Springs Court');
INSERT INTO Locations VALUES ('Rokietnica', '9 Donald Center');
INSERT INTO Locations VALUES ('Villasis', '483 Farwell Point');
INSERT INTO Locations VALUES ('Lyubymivka', '17 Hoepker Park');
INSERT INTO Locations VALUES ('Tarbes', '638 Karstens Center');
INSERT INTO Locations VALUES ('Bayantal', '33253 Hovde Parkway');
INSERT INTO Locations VALUES ('Xiaojinkou', '1148 Oakridge Terrace');
INSERT INTO Locations VALUES ('Syntul', '459 Mccormick Drive');
INSERT INTO Locations VALUES ('Wutongkou', '4503 Express Park');
INSERT INTO Locations VALUES ('Kōfu-shi', '5630 Forster Drive');
INSERT INTO Locations VALUES ('Cijangkar', '47 Jana Crossing');
INSERT INTO Locations VALUES ('Iperu', '703 Reindahl Hill');
INSERT INTO Locations VALUES ('Longquan', '06379 Maple Wood Place');
INSERT INTO Locations VALUES ('Pondokwungu', '35 8th Avenue');
INSERT INTO Locations VALUES ('Yanglinshi', '13 Little Fleur Alley');
INSERT INTO Locations VALUES ('Üydzen', '79062 Swallow Plaza');
INSERT INTO Locations VALUES ('Sukamaju', '6 Marcy Road');
INSERT INTO Locations VALUES ('Rochester', '831 Bay Road');
INSERT INTO Locations VALUES ('Mapaniqui', '958 Nova Lane');
INSERT INTO Locations VALUES ('Idfu', '02 Calypso Junction');
INSERT INTO Locations VALUES ('Karawatu', '6094 Talmadge Road');
INSERT INTO Locations VALUES ('La Cumbre', '7 Summerview Terrace');
INSERT INTO Locations VALUES ('Rantauambacang', '42 8th Alley');
INSERT INTO Locations VALUES ('Värnamo', '864 Lakeland Trail');
INSERT INTO Locations VALUES ('Petrolina', '48767 Dottie Pass');
INSERT INTO Locations VALUES ('Berestechko', '40 Northridge Circle');
INSERT INTO Locations VALUES ('Pucangkrajan', '52026 Arapahoe Road');
INSERT INTO Locations VALUES ('Płońsk', '63 Carpenter Hill');
INSERT INTO Locations VALUES ('Aubergenville', '13025 Hovde Hill');
INSERT INTO Locations VALUES ('Russas', '4901 Birchwood Road');
INSERT INTO Locations VALUES ('Strellc i Epërm', '20 Tennessee Road');
INSERT INTO Locations VALUES ('Kamieniec Podolski', '39 Sage Street');
INSERT INTO Locations VALUES ('Ajuy', '6 Transport Parkway');
INSERT INTO Locations VALUES ('Gantang', '99 Northwestern Point');
INSERT INTO Locations VALUES ('Chambéry', '00 Morning Alley');
INSERT INTO Locations VALUES ('Malinta', '44 Melby Junction');
INSERT INTO Locations VALUES ('Sịa', '087 Bonner Plaza');
INSERT INTO Locations VALUES ('Velikiy Ustyug', '425 Onsgard Terrace');
INSERT INTO Locations VALUES ('Richmond', '44 Goodland Way');
INSERT INTO Locations VALUES ('Krasnapollye', '111 Sugar Hill');
INSERT INTO Locations VALUES ('Gwangtan', '374 Washington Avenue');
INSERT INTO Locations VALUES ('Duas Igrejas', '81134 Annamark Park');
INSERT INTO Locations VALUES ('Dubrovka', '2 Burrows Circle');
INSERT INTO Locations VALUES ('Dizangué', '754 Calypso Circle');
INSERT INTO Locations VALUES ('Palecenan', '290 Redwing Plaza');
INSERT INTO Locations VALUES ('Washington', '94640 Crescent Oaks Point');
INSERT INTO Locations VALUES ('Kralupy nad Vltavou', '0652 Pine View Plaza');
INSERT INTO Locations VALUES ('Farkhah', '6 Linden Point');
INSERT INTO Locations VALUES ('Bhairab Bāzār', '3 Almo Lane');
INSERT INTO Locations VALUES ('Khorixas', '71957 Vernon Pass');
INSERT INTO Locations VALUES ('Konispol', '7965 Moulton Point');
INSERT INTO Locations VALUES ('Utrecht (stad)', '3498 Brown Street');
INSERT INTO Locations VALUES ('Mbanza Congo', '0621 Cardinal Drive');
INSERT INTO Locations VALUES ('Wufeng', '796 Sherman Junction');
INSERT INTO Locations VALUES ('El Banco', '40 Fallview Lane');
INSERT INTO Locations VALUES ('Błonie', '3685 Northview Parkway');
INSERT INTO Locations VALUES ('Huiqi', '08517 Hoepker Road');
INSERT INTO Locations VALUES ('Ambato Boeny', '0 Steensland Terrace');
INSERT INTO Locations VALUES ('Telde', '33060 Schlimgen Avenue');
INSERT INTO Locations VALUES ('Goyang-si', '708 Harbort Point');
INSERT INTO Locations VALUES ('Qingzhou', '19 Carey Street');
INSERT INTO Locations VALUES ('Bungoma', '442 Bay Trail');
INSERT INTO Locations VALUES ('Severnoye', '5789 Artisan Parkway');
INSERT INTO Locations VALUES ('Songkeng', '58 Declaration Alley');
INSERT INTO Locations VALUES ('El Triunfo', '386 Luster Pass');
INSERT INTO Locations VALUES ('Novyye Cherëmushki', '5 Bellgrove Crossing');
INSERT INTO Locations VALUES ('Peoria', '234 Butternut Lane');
INSERT INTO Locations VALUES ('Ust’-Uda', '302 Lyons Point');
INSERT INTO Locations VALUES ('Vitali', '182 South Point');
INSERT INTO Locations VALUES ('Karangkancana', '89052 Ruskin Point');
INSERT INTO Locations VALUES ('Venda Nova', '1 Lakewood Gardens Place');
INSERT INTO Locations VALUES ('San Rafael', '078 Eagle Crest Crossing');
INSERT INTO Locations VALUES ('Selce', '09857 Morrow Point');
INSERT INTO Locations VALUES ('Ziliang', '0883 Del Mar Hill');
INSERT INTO Locations VALUES ('Hongqi', '468 Amoth Court');
INSERT INTO Locations VALUES ('Żarów', '5 Northview Parkway');
INSERT INTO Locations VALUES ('Goseong', '0868 Anderson Park');
INSERT INTO Locations VALUES ('Ivot', '95 Nelson Park');
INSERT INTO Locations VALUES ('Cotuí', '5946 Lakewood Circle');
